version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "6060:6060"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
